kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    tier: backend
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"