kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"